### ISSUE TITLE
Console output is not left aligned

### ISSUE THREAD

**Issue by buddhike** [dillondesilva/codehelium#2]
Thanks for creating this project! 🙏🏾
I came across a very minor issue. When component is installed into a new app created with `create-react-app`, console output is not left aligned. See screenshot below.

<img width="925" alt="image" src="https://github.com/dillondesilva/codehelium/assets/2134633/1f2e0a9a-57b2-46f7-a6dd-7e19547ce35f">

**Comment by dillondesilva** [comment]
Hi dad🤣
Can you please try removing any references to App.css in the default App.js that is created with `create-react-app`? I had a similar issue but this seemed to work for me - let me know how it goes.

**Comment by buddhike** [comment]
Yup, that works! But I think the issue is that `text-left` class is not in `build.css` bundled into the component. See #3 for the proposed fixed.

**Comment by dillondesilva** [comment]
Great fix - its been merged to main now😎
